### ISSUE TITLE
Errors when upgrading to XCode 11.4

### ISSUE THREAD

**Issue by evanb2** [echobind/circleci-react-native-orb#13]
Apple is requiring all apps to be built using iOS 13+ starting June 30th, which requires XCode `11.X`. The default XCode image for this Orb is currently `10.1`. Manually setting the ios executor is throwing an error when building in CI.

My project's `config.yml`:
```
custom_executor:
    name: react-native/ios
    xcode_version: '11.4.1'
```

Error in CI:
![2020-05-20 at 11 35 AM](https://user-images.githubusercontent.com/11276439/82478404-19605a80-9a8e-11ea-9392-7b7802ea1a87.png)

Detailed error in the logs:
```
error `fsevents` unavailable (this watcher can only be used on Darwin). Run CLI with --verbose flag for more details
```

This seems to be caused by using `yarn` instead of `npm` in CI.

The `yarn install` step shows the following error:
```
Error running install script for optional dependency: "/Users/distiller/react-native/node_modules/fsevents: Command failed.
```

Using `npm install` succeeded with no errors.

1. Is there another fix for this besides using `npm`?
2. If not, what's the easiest way to override that using this Orb?
3. Is this Orb still maintained?

**Comment by evanb2** [comment]
Looks like specifying `node v10.11.0` also fixes the issue. Although the only way I was able to get that to work with my iOS job was by doing:
```
pre_build:
            - run:
                name: Force specific nodejs version
                command: |
                  export NODE_VERSION=$(cat .nvmrc)
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.1/install.sh | bash -s -- --no-use
                  echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                  echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
                  echo 'nvm install v10.11.0' >> $BASH_ENV
                  echo 'nvm alias default v10.11.0' >> $BASH_ENV
                  rm -rf node_modules
                  yarn install
```

I tried overriding the `react-native/node` executor but it didn't work:
```
- react-native/node:
    name: node
    custom_executor:
        name: react-native/node
        version: '10.11.0'
```

**Comment by cball** [comment]
Hey @evanb2! Appreciate the detail, and sorry you're having trouble with it. We're using the following executors in a recent project and things seem to be working ok:

```yml
executors:
  node:
    docker:
      - image: circleci/node:10.16.0-stretch
        environment:
          TERM: xterm
  android:
    docker:
      - image: circleci/android:api-28-node
    environment:
      - _JAVA_OPTIONS: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      - GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError"'
      - BUILD_THREADS: 2
      - FL_OUTPUT_DIR: output
  ios:
    macos:
      xcode: 11.3.1
    shell: /bin/bash --login -o pipefail
    resource_class: 'medium'
```

We'll take a look into this.
